import type { Metadata } from 'next'
import {NextUIProvider} from "@nextui-org/react";
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <NextUIProvider>
        <body>{children}</body>
      </NextUIProvider>
    </html>
  )
}
